# Generated by Django 6.0.3 on 2026-05-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_group_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blooddonor.donor'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='original_blood_group',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
