# Generated by Django 6.0.3 on 2026-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonor', '0002_bloodrequest_blood_group_changed_bloodrequest_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='token',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
